# Numpy 简介
导入numpy
Numpy是Python的一个很重要的第三方库，很多其他科学计算的第三方库都是以Numpy为基础建立的。

Numpy的一个重要特性是它的数组计算。

在使用Numpy之前，我们需要导入numpy包：

In [ ]:
import numpy as np

创建数组

In [2]:
# help(np.array)

In [3]:
#通过列表创建
np.array([1,2,3])

array([1, 2, 3])

In [4]:
#通过元组创建
np.array((1,2,3))

array([1, 2, 3])

In [5]:
np.array([[1,2,3,4],[5,6,7,8]])

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [6]:
np.array([
    [
        [1,2,3],
        [2,3,4]
    ],[
        [4,5,6],
        [5,6,7]
    ]
])

array([[[1, 2, 3],
        [2, 3, 4]],

       [[4, 5, 6],
        [5, 6, 7]]])

In [7]:
#通过zeros创建数组,创建一个元素为零的数组
np.zeros((3,3))

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [8]:
#生成元素为1的三行三列
np.ones((3,3))

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [9]:
np.empty((3,3))

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

其他创建方式

In [10]:
#range
np.arange(9)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [11]:
np.arange(1,9,2)

array([1, 3, 5, 7])

In [12]:
np.arange(9,0,-1)

array([9, 8, 7, 6, 5, 4, 3, 2, 1])

In [13]:
#linspace生成等差数列
np.linspace(1,10,4)

array([  1.,   4.,   7.,  10.])

In [14]:
#logspace 生成等比数列
# np.logspace(0,2,5)  #10的零次方开始，10的2次方结束，生成5个数
np.logspace(0,2,5,base=2)

array([ 1.        ,  1.41421356,  2.        ,  2.82842712,  4.        ])

In [15]:
#使用random创建随机函数
np.random.random((3,3))

array([[ 0.32449248,  0.6161898 ,  0.81407507],
       [ 0.46218236,  0.61562581,  0.69244943],
       [ 0.43686345,  0.7875988 ,  0.89182639]])

In [16]:
#生成3,3 的1-9的整数
np.random.randint(1,9,size=(2,3,4))

array([[[1, 5, 8, 3],
        [3, 6, 6, 8],
        [7, 7, 3, 6]],

       [[7, 7, 6, 5],
        [6, 6, 4, 4],
        [5, 4, 7, 3]]])

In [17]:
#标准正态分布
np.random.randn(3,3)

array([[ 0.62687044, -2.37993592,  0.81072004],
       [ 1.24286891, -1.35203761,  0.80440598],
       [ 0.80691323, -0.27418711, -0.37005454]])