# 数组方法

In [1]:
%pylab

Using matplotlib backend: Qt5Agg
Populating the interactive namespace from numpy and matplotlib


## 求和

In [3]:
a = array([[1,2,3],[4,5,6]])

求所有元素的和：

In [4]:
sum(a)

21

指定求和的维度：

沿着第一维求和：

In [7]:
sum(a,axis=0)

array([5, 7, 9])

沿着第二维求和：

In [9]:
sum(a,axis=1)

array([ 6, 15])

或者使用sum方法：

In [10]:
a.sum()

21

In [11]:
a.sum(axis=0)

array([5, 7, 9])

In [12]:
a.sum(axis=1)

array([ 6, 15])

## 求积

求所有元素的乘积：

In [13]:
a.prod()

720

或者使用函数形式：

In [15]:
prod(a,axis=0)

array([ 4, 10, 18])

## 求最大最小值

In [23]:
from numpy.random import rand
a = rand(3,4)
%precision 3 
a

array([[ 0.568,  0.049,  0.413,  0.683],
       [ 0.46 ,  0.246,  0.469,  0.039],
       [ 0.131,  0.73 ,  0.416,  0.754]])

%precision 3 表示精确到小数点后3位

全局最小：

In [25]:
a.min()

0.039

沿着某个轴的最小：

In [26]:
a.min(axis =0)

array([ 0.131,  0.049,  0.413,  0.039])

全局最大：

In [27]:
a.max()

0.754

沿着某个轴的最大：

In [28]:
a.max(axis=-1)

array([ 0.683,  0.469,  0.754])

## 最大最小值的位置

使用argmin,argmax方法：

In [31]:
a.min()

0.039

In [32]:
a.argmin()

7

In [33]:
a.max()

0.754

In [34]:
a.argmax()

11

## 均值

可以使用mean方法：

In [35]:
a = array([[1,2,3],[4,5,6]])

In [37]:
a.mean()

3.500

In [38]:
a.mean(axis=-1)

array([ 2.,  5.])

In [39]:
a.mean(axis=0)

array([ 2.5,  3.5,  4.5])

In [43]:
mean(a)

3.500

还可以使用average函数：

In [44]:
average(a,axis=0)

array([ 2.5,  3.5,  4.5])

average函数还支持加权平均：

In [45]:
average(a,axis =0,weights=[1,2])

array([ 3.,  4.,  5.])

## 标准差

用std方法计算标准差:

In [46]:
a.std(axis=1)

array([ 0.816,  0.816])

用var方法计算方差：

In [47]:
a.var(axis=1)

array([ 0.667,  0.667])

或者使用函数：

In [48]:
var(a,axis=1)

array([ 0.667,  0.667])

In [49]:
std(a,axis=1)

array([ 0.816,  0.816])

## clip方法

将数值限制在某个范围：

In [50]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [51]:
a.clip(3,5)

array([[3, 3, 3],
       [4, 5, 5]])

小于3的变成3，大于5的变成5

## ptp方法

计算最大值和最小值之差：

In [52]:
a.ptp(axis=1)

array([2, 2])

In [54]:
a.ptp()

5

## round方法

近似，默认到整数：

In [56]:
a = array([1.35,2.5,1.5])

.5的近似规则为近似到偶数值，可以参考

https://en.wikipedia.org/wiki/Rounding#Round_half_to_odd

In [57]:
a.round()

array([ 1.,  2.,  2.])

近似到一位小数：

In [58]:
a.round(decimals=1)

array([ 1.4,  2.5,  1.5])