矩阵切片 索引

In [22]:
import numpy as np

In [23]:
arr = np.random.randint(1,9,size=(2,3,4))
arr

array([[[5, 6, 7, 3],
        [2, 6, 3, 5],
        [3, 2, 8, 7]],

       [[6, 7, 4, 6],
        [2, 3, 5, 8],
        [1, 6, 6, 8]]])

In [24]:
print(arr[0][0][0])
print(arr[0][0][1])

5
6


In [25]:

print(arr[:,:,1:3])  #1/2维全切，column=all,步数从1到3,步长1
#print(arr[:,:,1:3:1])  #1/2维全切，column=all,步数从1到3,步长1
arr[:,:,1:3] = 3

[[[6 7]
  [6 3]
  [2 8]]

 [[7 4]
  [3 5]
  [6 6]]]


In [26]:
print(arr[:,:,1:3:2])  #1/2维全切，column=all,步数从1到3,步长2

[[[3]
  [3]
  [3]]

 [[3]
  [3]
  [3]]]


In [27]:
print(arr[0,:,1:3])  #切第1维，column=all,步数从1到3，步长1

[[3 3]
 [3 3]
 [3 3]]


In [28]:
print(arr[1,:,1:3])  #切第2维，column=all,步数从1到3，步长1

[[3 3]
 [3 3]
 [3 3]]


In [29]:
print(arr[:,1,1:3]) #1/2维全切，column=1,步数从1到3，步长1

[[3 3]
 [3 3]]


In [30]:
print(arr[:,2,1:3]) #1/2维全切，column=2,步数从1到3，步长1

[[3 3]
 [3 3]]


In [31]:
print(arr[1,2,1:3])

[3 3]


In [32]:
print(arr[0,1:3:2,1:3])

[[3 3]]


In [68]:
arr = np.random.randint(1,size=(2,4,8))

In [73]:
# print(arr[1:8:2,1:8:2,1:3])  #1/2维全切，column=all,步数从1到3,步长1
# print(arr)
arr[1:8:2,1:8:2,1:3] = 1
print(arr)

[[[0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0]]

 [[0 0 0 0 0 0 0 0]
  [0 1 1 0 0 0 0 0]
  [0 0 0 0 0 0 0 0]
  [0 1 1 0 0 0 0 0]]]
