# 数组排序

In [41]:
%pylab

Using matplotlib backend: Qt5Agg
Populating the interactive namespace from numpy and matplotlib


## sort函数

In [42]:
names = array(['bob','sue','jan','ad'])
weights = array([20.8,93.2,53.4,61.8])
sort(weights)

array([ 20.8,  53.4,  61.8,  93.2])

sort返回的结果是从小到大排序的。

## argsort函数

argsort返回从小到大的排序在数组中的索引位置：

In [43]:
ordered_indices = argsort(weights)
ordered_indices

array([0, 2, 3, 1], dtype=int32)

In [44]:
weights[ordered_indices]

array([ 20.8,  53.4,  61.8,  93.2])

In [45]:
names[ordered_indices]

array(['bob', 'jan', 'ad', 'sue'],
      dtype='<U3')

使用函数并不会改变原来数组的值：

In [46]:
weights

array([ 20.8,  93.2,  53.4,  61.8])

## sort和argsort方法

数值也支持方法操作：

In [47]:
data = array([20.8,93.2,53.4,61.8])
data.argsort()

array([0, 2, 3, 1], dtype=int32)

argsort方法和argsort函数的使用没区别，也不会改变数组的值

In [48]:
data

array([ 20.8,  93.2,  53.4,  61.8])

但是sort方法会改变数组的值：

In [49]:
data.sort()

In [50]:
data

array([ 20.8,  53.4,  61.8,  93.2])

## 二维数组排序

对于多维数组，sort方法默认沿着最后一维开始排序：

In [51]:
a = array([[.2,.1,.5],
         [.4,.8,.3],
         [.9,.6,.7]])
a

array([[ 0.2,  0.1,  0.5],
       [ 0.4,  0.8,  0.3],
       [ 0.9,  0.6,  0.7]])

对于二维数组，默认相当于对每一行进行排序：

改变轴，对每一列进行排序：

In [52]:
sort(a,axis=0)

array([[ 0.2,  0.1,  0.3],
       [ 0.4,  0.6,  0.5],
       [ 0.9,  0.8,  0.7]])

## searchsorted函数

    searchsorted(sorted_array,values)

searchsorted接受两个函数，其中，第一个必需是已排序的数组。

In [56]:
sorted_array = linspace(0,1,5)

values = array([.1,.8,.3,.12,.5,.25])

In [58]:
sorted_array

array([ 0.  ,  0.25,  0.5 ,  0.75,  1.  ])

In [57]:
searchsorted(sorted_array, values)

array([1, 4, 2, 1, 2, 1], dtype=int32)

排序数组：

|0|1|2|3|4|
|-|-|-|-|-|
|0.0|0.25|0.5|0.75|1.0

数值：

|值|0.1|0.8|0.3|0.12|0.5|0.25|
|-|-|-|-|-|-|-|
|插入位置|1|4|2|1|2|1|

`searchsorted` 返回的值相当于保持第一个数组的排序性质不变，将第二个数组中的值插入第一个数组中的位置：

例如 `0.1` 在 [0.0, 0.25) 之间，所以插入时应当放在第一个数组的索引 `1` 处，故第一个返回值为 `1`。

In [65]:
from numpy.random import rand
data = rand(100)
data.sort()

不加括号，默认是元祖：

In [66]:
data

array([ 0.01326787,  0.02019924,  0.022693  ,  0.03011729,  0.03477448,
        0.05276822,  0.05337634,  0.06196816,  0.08419036,  0.09294402,
        0.09491983,  0.09903121,  0.12199805,  0.13794742,  0.14661397,
        0.14999338,  0.16618643,  0.17284061,  0.17370873,  0.18711429,
        0.19107019,  0.22629769,  0.26820909,  0.27227244,  0.30951476,
        0.31006863,  0.3164793 ,  0.3296144 ,  0.33589373,  0.33590673,
        0.33737576,  0.34115926,  0.3429105 ,  0.34517408,  0.3569934 ,
        0.36934844,  0.38268565,  0.39375529,  0.39760667,  0.39798931,
        0.40704821,  0.42222163,  0.4421603 ,  0.45324164,  0.46072486,
        0.46549058,  0.46664516,  0.47009308,  0.48860757,  0.52046336,
        0.52168674,  0.52295019,  0.53114733,  0.53257409,  0.53660409,
        0.54948561,  0.55242322,  0.55366594,  0.59894015,  0.6273889 ,
        0.62766808,  0.63358545,  0.65771519,  0.67338914,  0.68060718,
        0.68087946,  0.68901842,  0.69070993,  0.73668461,  0.75

In [63]:
bounds = .4,.6
bounds

(0.4, 0.6)

返回这两个对应的插入位置：

In [71]:
low_idx,high_idx = searchsorted(data, bounds)

利用插入位置，将数组中的所有在这两个值之间的值提取出来：

In [73]:
data[low_idx:high_idx]

array([ 0.40704821,  0.42222163,  0.4421603 ,  0.45324164,  0.46072486,
        0.46549058,  0.46664516,  0.47009308,  0.48860757,  0.52046336,
        0.52168674,  0.52295019,  0.53114733,  0.53257409,  0.53660409,
        0.54948561,  0.55242322,  0.55366594,  0.59894015])