# 数组形状

In [1]:
%pylab

Using matplotlib backend: Qt5Agg
Populating the interactive namespace from numpy and matplotlib


## 修改数组的形状

In [2]:
a = arange(6)
a

array([0, 1, 2, 3, 4, 5])

将形状修改为2乘3：

In [4]:
a.shape = 2,3

In [5]:
a

array([[0, 1, 2],
       [3, 4, 5]])

与之对应的方法是reshape,但它不会修改原来数组的值，而是返回一个新的数组：

In [6]:
a.reshape(3,2)

array([[0, 1],
       [2, 3],
       [4, 5]])

In [7]:
a

array([[0, 1, 2],
       [3, 4, 5]])

shape和reshape方法不能改变数组中元素的总数，否则会报错：

In [9]:
a.reshape(4,2)

ValueError: cannot reshape array of size 6 into shape (4,2)

## 使用newaxis增加数组维数

In [10]:
a = arange(3)
shape(a)

(3,)

In [12]:
y = a[newaxis,:]
shape(y)

(1, 3)

根据插入位置的不同，可以返回不同形状的数组：

In [13]:
y = a[:,newaxis]
shape(y)

(3, 1)

插入多个新维度：

In [15]:
y = a[newaxis,newaxis,:]
shape(y)

(1, 1, 3)

## squeeze方法去除多余的轴

In [17]:
a = arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [20]:
a.reshape(2,1,3)

array([[[0, 1, 2]],

       [[3, 4, 5]]])

In [21]:
b = a.squeeze()
b.shape

(6,)

squeeze返回一个将所有长度为1的维度去除的新数组.

## 数组转置

使用transpose返回数组的转置，本质上是将所有维度反过来：

In [29]:
a.shape=2,3

In [30]:
a

array([[0, 1, 2],
       [3, 4, 5]])

In [31]:
a.transpose()

array([[0, 3],
       [1, 4],
       [2, 5]])

或者使用缩写属性：

In [32]:
a.T

array([[0, 3],
       [1, 4],
       [2, 5]])

注意：

.对于复数数组，转置并不反悔复共轭，只是单纯的交换轴的位置

.转置可以作用于多维数组

In [34]:
a = arange(60)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [36]:
a.shape = 3,4,5
a

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39]],

       [[40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59]]])

In [53]:
b = a.T

In [54]:
b.shape

(6,)

In [55]:
b

array([0, 1, 2, 3, 4, 5])

转置只是交换了轴的位置。

另一方面，转置返回的是对原数组的另一种view,所以改变转置会改变原来数组的值

In [59]:
a = arange(6)
a.shape =(2,3)
a

array([[0, 1, 2],
       [3, 4, 5]])

修改转置：

In [60]:
b = a.T
b

array([[0, 3],
       [1, 4],
       [2, 5]])

In [61]:
b[0,1] = 30

In [62]:
a

array([[ 0,  1,  2],
       [30,  4,  5]])

In [63]:
b

array([[ 0, 30],
       [ 1,  4],
       [ 2,  5]])

原数组的值也改变：

## 数组连接

有时我们需要将不同的数组按照一定的顺序连接起来：

    concatenate((a0,a1,....,aN),axis = 0)
    

注意，这些数组要用()包括到一个元组中去。

除了给定的轴外，这些数组其他轴的长度必须是一样的。

In [65]:
x = array([[0,1,2],
          [10,11,12]
          ])
y =  array([[50,51,52],
           [60,61,62]
           ])
x.shape

(2, 3)

In [66]:
y.shape

(2, 3)

默认沿着第一维进行连接：

In [67]:
z = concatenate((x,y))
z

array([[ 0,  1,  2],
       [10, 11, 12],
       [50, 51, 52],
       [60, 61, 62]])

In [68]:
z.shape

(4, 3)

沿着第二维进行连接：

In [69]:
z = concatenate((x,y),axis=1)
z

array([[ 0,  1,  2, 50, 51, 52],
       [10, 11, 12, 60, 61, 62]])

In [70]:
z.shape

(2, 6)

In [71]:
z = array((x,y))

In [72]:
z.shape

(2, 2, 3)

事实上，Numpy提供了分别对应这三种情况的函数:

.vstack

.hstack

.dstack

In [73]:
vstack((x,y)).shape

(4, 3)

In [74]:
hstack((x,y)).shape

(2, 6)

In [75]:
dstack((x,y)).shape

(2, 3, 2)

## Flatten数组

flatten方法的作用是将多维数组转化为1维数组：

In [76]:
a = array([[0,1],
          [2,3]
          ])
b = a.flatten()
b

array([0, 1, 2, 3])

返回的是数组的复制，因此，改变b并不会影响a的值：

In [77]:
b[0] = 10
b

array([10,  1,  2,  3])

In [78]:
a

array([[0, 1],
       [2, 3]])

## flat属性

还可以使用数组自带的flat属性：

In [79]:
a.flat

a.flat相当于返回了所有元组组成的一个迭代器：

In [80]:
b = a.flat

In [81]:
b[0]

0

但此时修改b的值会影响a:

In [82]:
b

In [83]:
b[0] = 10

In [84]:
a

array([[10,  1],
       [ 2,  3]])

In [85]:
a.flat[:]

array([10,  1,  2,  3])

## ravel方法

除此之外，还可以使用ravel方法，ravel使用高效的表达方法：

In [87]:
a = array([[0,1],
          [2,3]
          ])
b = a.ravel()

In [88]:
b

array([0, 1, 2, 3])

修改b会改变a:

In [89]:
b[0] = 10
a

array([[10,  1],
       [ 2,  3]])

但另一种情况下：

In [90]:
a = array([[0,1],
          [2,3]
          ])
aa = a.transpose()
b = aa.ravel()
b

array([0, 2, 1, 3])

In [91]:
b[0] = 10

In [92]:
aa

array([[0, 2],
       [1, 3]])

可以看到，在这种情况下，修改b并不会改变aa的值，原因是我们用来ravel的对象aa本身是a的一个view

## atleast_xd函数

保证数组至少有x维：

In [93]:
x = 1
atleast_1d(x)

array([1])

In [94]:
a = array([1,2,3])
b = atleast_2d(a)
b.shape

(1, 3)

In [95]:
b

array([[1, 2, 3]])

In [96]:
c = atleast_3d(b)
c.shape

(1, 3, 1)

In [97]:
c

array([[[1],
        [2],
        [3]]])

`x` 可以取值 1，2，3。

在**Scipy**库中，这些函数被用来保证输入满足一定的条件：“ 

|用法|**Scipy**中出现次数|
|-|-|
|value.flaten() <br> value.flat <br>  value.ravel() |     ~2000次
| atleast_1d(value) <br> atleast_2d(value)  |~700次
| asarray(value)    |~4000次