In [20]:
import numpy as np

In [21]:
arr=np.random.randint(1,9,size=(8,4))
arr

array([[6, 2, 4, 4],
       [7, 7, 4, 8],
       [2, 6, 6, 5],
       [2, 8, 6, 4],
       [8, 8, 7, 2],
       [1, 1, 2, 7],
       [2, 2, 4, 3],
       [5, 3, 4, 5]])

In [22]:
#获取0,3,5行数据
print(arr[[0,3,5]])

[[6 2 4 4]
 [2 8 6 4]
 [1 1 2 7]]


In [23]:
#获取第0行第0个，第3行的第3个，第5行的第2个
print(arr[[0,3,5],[0,3,2]])
print(arr[(0,3,5),(0,3,2)])

[6 4 2]
[6 4 2]


In [24]:
arr = np.zeros((8,8))

In [25]:
print(arr)

[[ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]]


In [26]:
arr[0:8:2,0:8:2]=1

In [27]:
print(arr)

[[ 1.  0.  1.  0.  1.  0.  1.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 1.  0.  1.  0.  1.  0.  1.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 1.  0.  1.  0.  1.  0.  1.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 1.  0.  1.  0.  1.  0.  1.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]]
