In [6]:
import numpy as np

# 常用一元函数

In [7]:
arr = np.random.randint(1,9,size=(3,3))
print(arr)
print(np.sqrt(arr))  #开平方
print(np.exp(arr))

[[1 3 7]
 [1 3 3]
 [1 6 3]]
[[ 1.          1.73205081  2.64575131]
 [ 1.          1.73205081  1.73205081]
 [ 1.          2.44948974  1.73205081]]
[[    2.71828183    20.08553692  1096.63315843]
 [    2.71828183    20.08553692    20.08553692]
 [    2.71828183   403.42879349    20.08553692]]


In [8]:
print(arr.min(axis = 0))
print(arr.max(axis = 0))
print(arr.mean(axis = 0))

[1 3 3]
[1 6 7]
[ 1.          4.          4.33333333]


In [9]:
print(arr.std(axis = 0))

[ 0.          1.41421356  1.88561808]


In [10]:
# help(np.where)

In [11]:
np.where([[True,False],[True,True]],
        [[1,2,],[3,4]],
        [[9,8],[7,6]])


array([[1, 8],
       [3, 4]])

In [12]:
np.where([[0,1],[1,0]])

(array([0, 1], dtype=int32), array([1, 0], dtype=int32))

In [13]:
x = np.arange(9).reshape(3,3)
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [14]:
np.where(x>5)

(array([2, 2, 2], dtype=int32), array([0, 1, 2], dtype=int32))

In [15]:
y = x[np.where(x >3.0)]
print(y)

[4 5 6 7 8]


In [16]:
np.where([[True,False],[True,True]],
        [[1,2,],[3,4]],
        [[9,8],[7,6]])
# 1、这里x,y是可选参数，condition是条件，这三个输入参数都是array_like的形式；而且三者的维度相同
# 2、当conditon的某个位置的为true时，输出x的对应位置的元素，否则选择y对应位置的元素；
# 3、如果只有参数condition，则函数返回为true的元素的坐标位置信息；

array([[1, 8],
       [3, 4]])

In [17]:
##zip