In [1]:
import numpy as np

# 常用一元函数

In [10]:
arr = np.random.randint(1,9,size=(3,3))
print(arr)
print(np.sqrt(arr))  #开平方
print(np.exp(arr))

[[2 6 8]
 [2 2 4]
 [4 2 6]]
[[ 1.41421356  2.44948974  2.82842712]
 [ 1.41421356  1.41421356  2.        ]
 [ 2.          1.41421356  2.44948974]]
[[    7.3890561    403.42879349  2980.95798704]
 [    7.3890561      7.3890561     54.59815003]
 [   54.59815003     7.3890561    403.42879349]]


In [11]:
print(arr.min(axis = 0))
print(arr.max(axis = 0))
print(arr.mean(axis = 0))

[2 2 4]
[4 6 8]
[ 2.66666667  3.33333333  6.        ]


In [13]:
print(arr.std(axis = 0))

[ 0.94280904  1.88561808  1.63299316]


In [15]:
help(np.where)

Help on built-in function where in module numpy.core.multiarray:

where(...)
    where(condition, [x, y])
    
    Return elements, either from `x` or `y`, depending on `condition`.
    
    If only `condition` is given, return ``condition.nonzero()``.
    
    Parameters
    ----------
    condition : array_like, bool
        When True, yield `x`, otherwise yield `y`.
    x, y : array_like, optional
        Values from which to choose. `x`, `y` and `condition` need to be
        broadcastable to some shape.
    
    Returns
    -------
    out : ndarray or tuple of ndarrays
        If both `x` and `y` are specified, the output array contains
        elements of `x` where `condition` is True, and elements from
        `y` elsewhere.
    
        If only `condition` is given, return the tuple
        ``condition.nonzero()``, the indices where `condition` is True.
    
    See Also
    --------
    nonzero, choose
    
    Notes
    -----
    If `x` and `y` are given and input arrays are

In [37]:
np.where([[True,False],[True,True]],
        [[1,2,],[3,4]],
        [[9,8],[7,6]])


array([[1, 8],
       [3, 4]])

In [42]:
np.where([[0,1],[1,0]])

(array([0, 1], dtype=int32), array([1, 0], dtype=int32))

In [43]:
x = np.arange(9).reshape(3,3)
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [44]:
np.where(x>5)

(array([2, 2, 2], dtype=int32), array([0, 1, 2], dtype=int32))

In [53]:
y = x[np.where(x >3.0)]
print(y)

[4 5 6 7 8]


In [55]:
np.where([[True,False],[True,True]],
        [[1,2,],[3,4]],
        [[9,8],[7,6]])
# 1、这里x,y是可选参数，condition是条件，这三个输入参数都是array_like的形式；而且三者的维度相同
# 2、当conditon的某个位置的为true时，输出x的对应位置的元素，否则选择y对应位置的元素；
# 3、如果只有参数condition，则函数返回为true的元素的坐标位置信息；

array([[1, 8],
       [3, 4]])

In [ ]:
##zip