# 矩阵切片 索引

In [6]:
import numpy as np

In [7]:
arr = np.random.randint(1,9,size=(2,3,4))
arr

array([[[8, 1, 7, 3],
        [7, 4, 7, 4],
        [3, 4, 6, 1]],

       [[7, 3, 7, 5],
        [6, 7, 4, 2],
        [1, 6, 5, 5]]])

In [8]:
print(arr[0][0][0])
print(arr[0][0][1])

8
1


In [9]:

print(arr[:,:,1:3])  #1/2维全切，column=all,步数从1到3,步长1
#print(arr[:,:,1:3:1])  #1/2维全切，column=all,步数从1到3,步长1
arr[:,:,1:3] = 3

[[[1 7]
  [4 7]
  [4 6]]

 [[3 7]
  [7 4]
  [6 5]]]


In [10]:
print(arr[:,:,1:3:2])  #1/2维全切，column=all,步数从1到3,步长2

[[[3]
  [3]
  [3]]

 [[3]
  [3]
  [3]]]


In [11]:
print(arr[0,:,1:3])  #切第1维，column=all,步数从1到3，步长1

[[3 3]
 [3 3]
 [3 3]]


In [12]:
print(arr[1,:,1:3])  #切第2维，column=all,步数从1到3，步长1

[[3 3]
 [3 3]
 [3 3]]


In [13]:
print(arr[:,1,1:3]) #1/2维全切，column=1,步数从1到3，步长1

[[3 3]
 [3 3]]


In [14]:
print(arr[:,2,1:3]) #1/2维全切，column=2,步数从1到3，步长1

[[3 3]
 [3 3]]


In [15]:
print(arr[1,2,1:3])

[3 3]


In [16]:
print(arr[0,1:3:2,1:3])

[[3 3]]


In [17]:
arr = np.random.randint(1,size=(2,4,8))

In [18]:
# print(arr[1:8:2,1:8:2,1:3])  #1/2维全切，column=all,步数从1到3,步长1
# print(arr)
arr[1:8:2,1:8:2,1:3] = 1
print(arr)

[[[0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0]]

 [[0 0 0 0 0 0 0 0]
  [0 1 1 0 0 0 0 0]
  [0 0 0 0 0 0 0 0]
  [0 1 1 0 0 0 0 0]]]


In [23]:
a = np.array([[ 0, 1, 2, 3, 4, 5],
           [10,11,12,13,14,15],
           [20,21,22,23,24,25],
           [30,31,32,33,34,35],
           [40,41,42,43,44,45],
           [50,51,52,53,54,55]])
a

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

想得到第一行的第4和第5个元素：

In [24]:
a[0,3:5]

array([3, 4])

得到最后两行的最后两列：

In [25]:
a[4:,4:]

array([[44, 45],
       [54, 55]])

得到第三列：

In [27]:
a[:,2]

array([ 2, 12, 22, 32, 42, 52])

每一维都支持切片的规则，包括负索引：
    
     [lower:upper:step]
        
例如：取出，3,5行的奇数列：

In [28]:
a[2::2,::2]

array([[20, 22, 24],
       [40, 42, 44]])

## 切片是引用

切片在内存中使用的是引用机制

In [29]:
a = np.array([0,1,2,3,4])
b = a[2:4]
b

array([2, 3])

引用机制意味着，Python并没有为 b 分配新的空间来存储它的值，而是让 b 指向了 a 所分配的内存空间，因此，改变 b 会改变 a 的值：

In [31]:
b[0] = 10
a

array([ 0,  1, 10,  3,  4])

而这种现象在列表中并不会出现:

In [32]:
a = [1,2,3,4,5]
b = a[2:3]
b[0] = 1231
a

[1, 2, 3, 4, 5]

这样做的好处在于，对于很大的数组，不用大量复制多余的值，节约了空间。

缺点在于，可能出现改变一个值改变另一个值的情况。

一个解决方法是使用copy()方法产生一个复制，这个复制会申请新的内存