In [40]:
import numpy as np

# 花式索引

切片支持支持连续或者等间隔的切片操作，要想实现任意位置的操作，需要使用花式索引，fancy slicing

## 一维花式索引

与range函数类似，我们可以使用arrange函数来产生等差数组

In [41]:
a = np.arange(0,80,10)
a

array([ 0, 10, 20, 30, 40, 50, 60, 70])

花式索引需要制定索引位置：

In [42]:
indices = [1,2,-3]
y = a[indices]
y

array([10, 20, 50])

还可以使用布尔数组来花式索引：

In [43]:
mask=np.array([0,1,1,0,0,1,0,0],dtype=bool)
a[mask]

array([10, 20, 50])

或者用布尔表达式生成mask,选出了所有大于0.5的值：

In [44]:
a = np.random.randn(10)
a

array([-0.97915094,  1.02718913, -1.13163894, -0.45264665, -0.97173512,
       -1.97552095, -0.04634015, -1.0915336 , -1.91611219,  0.33915288])

In [45]:
mask = a > 0.5
a[mask]

array([ 1.02718913])

mask必须是布尔数组。

## 二维花式索引

In [46]:
a = np.array([[ 0, 1, 2, 3, 4, 5],
           [10,11,12,13,14,15],
           [20,21,22,23,24,25],
           [30,31,32,33,34,35],
           [40,41,42,43,44,45],
           [50,51,52,53,54,55]])

In [47]:
a

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

对于二维花式索引，我们需要给定 row 和 col 的值：

In [48]:
a[(0,1,2,3,4),(1,2,3,4,5)]

array([ 1, 12, 23, 34, 45])

返回的是一条次对角线上的5个值

In [49]:
a[3:,[0,2,5]]

array([[30, 32, 35],
       [40, 42, 45],
       [50, 52, 55]])

返回的是最后一行的第1,3,5列。
也可以用mask进行索引：

In [52]:
mask = array([1,0,1,0,0,1],dtype=bool)
a[mask,2]

array([ 2, 22, 52])

与切片不同，花式索引返回的是原对象的一个复制而不是引用。

## 不完全索引

只给定索引的时候，返回整行：

In [59]:
y = a[:3]

In [60]:
y

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25]])

也可以用花式索引取出第2,3,5行：

In [63]:
condition = np.array([0,1,1,0,1,0],dtype=bool)
a[condition]

array([[10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [40, 41, 42, 43, 44, 45]])

## 三维华式索引

In [71]:
a = np.arange(64)
a.shape=4,4,4
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31]],

       [[32, 33, 34, 35],
        [36, 37, 38, 39],
        [40, 41, 42, 43],
        [44, 45, 46, 47]],

       [[48, 49, 50, 51],
        [52, 53, 54, 55],
        [56, 57, 58, 59],
        [60, 61, 62, 63]]])

In [75]:
y = a[:,:,[2,-1]]
y

array([[[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]],

       [[18, 19],
        [22, 23],
        [26, 27],
        [30, 31]],

       [[34, 35],
        [38, 39],
        [42, 43],
        [46, 47]],

       [[50, 51],
        [54, 55],
        [58, 59],
        [62, 63]]])

In [83]:
y = a[2:,2:,[2,-1]]
y

array([[[42, 43],
        [46, 47]],

       [[58, 59],
        [62, 63]]])

In [53]:
arr=np.random.randint(1,9,size=(8,4))
arr

array([[5, 1, 7, 4],
       [1, 2, 7, 6],
       [6, 1, 5, 1],
       [6, 7, 6, 8],
       [5, 3, 1, 2],
       [7, 5, 1, 5],
       [2, 7, 3, 6],
       [8, 4, 8, 8]])

In [54]:
#获取0,3,5行数据
print(arr[[0,3,5]])

[[5 1 7 4]
 [6 7 6 8]
 [7 5 1 5]]


In [55]:
#获取第0行第0个，第3行的第3个，第5行的第2个
print(arr[[0,3,5],[0,3,2]])
print(arr[(0,3,5),(0,3,2)])

[5 8 1]
[5 8 1]


In [56]:
arr = np.zeros((8,8))

In [57]:
print(arr)

[[ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]]


In [58]:
arr[0:8:2,0:8:2]=1

In [27]:
print(arr)

[[ 1.  0.  1.  0.  1.  0.  1.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 1.  0.  1.  0.  1.  0.  1.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 1.  0.  1.  0.  1.  0.  1.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 1.  0.  1.  0.  1.  0.  1.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]]
