In [2]:
import numpy as np

# 常用一元函数

In [3]:
arr = np.random.randint(1,9,size=(3,3))
print(arr)
print(np.sqrt(arr))  #开平方
print(np.exp(arr))

[[8 2 2]
 [2 4 7]
 [1 6 5]]
[[ 2.82842712  1.41421356  1.41421356]
 [ 1.41421356  2.          2.64575131]
 [ 1.          2.44948974  2.23606798]]
[[  2.98095799e+03   7.38905610e+00   7.38905610e+00]
 [  7.38905610e+00   5.45981500e+01   1.09663316e+03]
 [  2.71828183e+00   4.03428793e+02   1.48413159e+02]]


In [4]:
print(arr.min(axis = 0))
print(arr.max(axis = 0))
print(arr.mean(axis = 0))

[1 2 2]
[8 6 7]
[ 3.66666667  4.          4.66666667]


In [5]:
print(arr.std(axis = 0))

[ 3.09120617  1.63299316  2.05480467]


## Where语句

where(array)
where函数会返回所有非零元素的索引

## 一维数组

In [6]:
a = np.array([0,12,5,20])

判断数组中的元素是不是大于10：

In [7]:
a > 10

array([False,  True, False,  True], dtype=bool)

数组中所有大于10的元素的索引位置：

In [9]:
np.where(a > 10)

(array([1, 3], dtype=int32),)

注意到 where 的返回值是一个元组。

使用元组是由于 where 可以对多维数组使用，此时返回值就是多维的。

在使用的时候，我们可以这样：

In [12]:
indices = np.where(a>10)
indices = indices[0]
indices

array([1, 3], dtype=int32)

或者：

In [13]:
indices = np.where(a > 10)[0]
indices

array([1, 3], dtype=int32)

可以直接用where的返回值进行索引:

In [14]:
loc =np.where(a >10)
a[loc]

array([12, 20])

## 多维数组

考虑二维数组：


In [17]:
a = np.array([[0,12,5,20],
             [1,2,13,12]])
loc = np.where(a > 10)

In [18]:
np.where([[True,False],[True,True]],
        [[1,2,],[3,4]],
        [[9,8],[7,6]])
loc

(array([0, 0, 1, 1], dtype=int32), array([1, 3, 2, 3], dtype=int32))

也可以直接用来索引a:

In [19]:
a[loc]

array([12, 20, 13, 12])

或者可以这样：

In [22]:
rows ,cols = np.where(a>10)
rows

array([0, 0, 1, 1], dtype=int32)

In [23]:
cols

array([1, 3, 2, 3], dtype=int32)

In [24]:
a[rows,cols]

array([12, 20, 13, 12])

再看一个例子：

In [26]:
a = np.arange(25)
a.shape = 5,5
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [27]:
a > 12

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]], dtype=bool)

In [28]:
np.where(a > 12)

(array([2, 2, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4], dtype=int32),
 array([3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4], dtype=int32))

In [12]:
np.where([[0,1],[1,0]])

(array([0, 1], dtype=int32), array([1, 0], dtype=int32))

In [13]:
x = np.arange(9).reshape(3,3)
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [14]:
np.where(x>5)

(array([2, 2, 2], dtype=int32), array([0, 1, 2], dtype=int32))

In [15]:
y = x[np.where(x >3.0)]
print(y)

[4 5 6 7 8]


In [16]:
np.where([[True,False],[True,True]],
        [[1,2,],[3,4]],
        [[9,8],[7,6]])
# 1、这里x,y是可选参数，condition是条件，这三个输入参数都是array_like的形式；而且三者的维度相同
# 2、当conditon的某个位置的为true时，输出x的对应位置的元素，否则选择y对应位置的元素；
# 3、如果只有参数condition，则函数返回为true的元素的坐标位置信息；

array([[1, 8],
       [3, 4]])

In [17]:
##zip