# 矩阵

使用mat方法将2维数组转化为矩阵：

In [1]:
import numpy as np 
a = np.array([[1,2,4],
              [2,5,3],
              [7,8,9]]
            )
A = np.mat(a)
A

matrix([[1, 2, 4],
        [2, 5, 3],
        [7, 8, 9]])

也可以使用Matlab的语法传入一个字符串来生成矩阵：

In [4]:
A=np.mat('1,2,3;4,5,6;7,8,9')

In [5]:
A

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

利用分块创建新的矩阵：

In [7]:
a = np.array([[1,2],
             [3,4]
             ])
b = np.array([[10,20],
             [30,40]
             ])
np.bmat('a,b;b,a')

matrix([[ 1,  2, 10, 20],
        [ 3,  4, 30, 40],
        [10, 20,  1,  2],
        [30, 40,  3,  4]])

矩阵与向量的乘法：

In [8]:
x = np.array([[1],[2],[3]])

In [9]:
x

array([[1],
       [2],
       [3]])

In [10]:
A

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [11]:
A*x

matrix([[14],
        [32],
        [50]])

In [12]:
A*A.I

matrix([[ 0.,  0.,  0.],
        [-4.,  0., -4.],
        [ 0.,  0.,  0.]])

In [13]:
A** 4

matrix([[ 7560,  9288, 11016],
        [17118, 21033, 24948],
        [26676, 32778, 38880]])