In [5]:
import numpy as np
import pandas as pd
from pandas import Series,DataFrame

In [6]:
m= np.random.rand(2,3,4)

In [7]:
print(m)

[[[ 0.60269788  0.55738893  0.83376704  0.63237362]
  [ 0.6798727   0.61622292  0.01949858  0.49306229]
  [ 0.89410407  0.50722457  0.8990403   0.23189915]]

 [[ 0.67639371  0.76244316  0.44746143  0.46236213]
  [ 0.47056274  0.54370722  0.41090397  0.622032  ]
  [ 0.19619915  0.72613632  0.77867691  0.28232254]]]


In [8]:
arr2 = np.zeros((8,8))
arr2.shape

(8, 8)

In [9]:
print(arr2)

[[ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]]


In [10]:
arr2[0:8:2,0:8:2]=1
print(arr2)

[[ 1.  0.  1.  0.  1.  0.  1.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 1.  0.  1.  0.  1.  0.  1.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 1.  0.  1.  0.  1.  0.  1.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 1.  0.  1.  0.  1.  0.  1.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]]


In [11]:
#arr3=np.zeros((10,10)) 
arr3=np.random.randint(1,size=(10,10))

In [12]:
print(arr3)

[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]


In [13]:
arr3[1:9,1:9]=1
print(arr3)
 

[[0 0 0 0 0 0 0 0 0 0]
 [0 1 1 1 1 1 1 1 1 0]
 [0 1 1 1 1 1 1 1 1 0]
 [0 1 1 1 1 1 1 1 1 0]
 [0 1 1 1 1 1 1 1 1 0]
 [0 1 1 1 1 1 1 1 1 0]
 [0 1 1 1 1 1 1 1 1 0]
 [0 1 1 1 1 1 1 1 1 0]
 [0 1 1 1 1 1 1 1 1 0]
 [0 0 0 0 0 0 0 0 0 0]]


In [14]:
s1 = pd.Series(np.arange(5))
print(s1)

0    0
1    1
2    2
3    3
4    4
dtype: int32


In [15]:
s1.index=['a','b','c','d','e']
print(s1.keys)
print(s1.values)

<bound method Series.keys of a    0
b    1
c    2
d    3
e    4
dtype: int32>
[0 1 2 3 4]


In [16]:
print(s1)

a    0
b    1
c    2
d    3
e    4
dtype: int32


In [17]:
df01=pd.DataFrame({'语文':[70,80,90],
                    '数学':[97,98,100],
                    '英语':[85,96,96]})
print(df01)

    数学  英语  语文
0   97  85  70
1   98  96  80
2  100  96  90


In [18]:
df01.mean()

数学    98.333333
英语    92.333333
语文    80.000000
dtype: float64

In [19]:
df01.min()

数学    97
英语    85
语文    70
dtype: int64

In [20]:
df01.max()

数学    100
英语     96
语文     90
dtype: int64

In [27]:
df01['python']=[np.NaN,np.NaN,np.NaN]
df01

数学  英语  语文  python
0   97  85  70     NaN
1   98  96  80     NaN
2  100  96  90     NaN

In [28]:
df01['python']=[100,77,89]
df01

数学  英语  语文  python
0   97  85  70     100
1   98  96  80      77
2  100  96  90      89