In [110]:
import numpy as np
import pandas as pd
from pandas import Series,DataFrame

In [111]:
m= np.random.rand(2,3,4)

In [112]:
print(m)

[[[ 0.42594854  0.908876    0.40996061  0.54844383]
  [ 0.24301482  0.33312855  0.29150106  0.43166411]
  [ 0.88630596  0.44256483  0.49988176  0.46792721]]

 [[ 0.19743192  0.2131523   0.71352454  0.15021659]
  [ 0.02382061  0.78680048  0.09815954  0.64616605]
  [ 0.28738566  0.61819966  0.76902727  0.35760511]]]


In [113]:
arr2 = np.zeros((8,8))
arr2.shape

(8, 8)

In [114]:
print(arr2)

[[ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]]


In [115]:
arr2[0:8:2,0:8:2]=1
print(arr2)

[[ 1.  0.  1.  0.  1.  0.  1.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 1.  0.  1.  0.  1.  0.  1.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 1.  0.  1.  0.  1.  0.  1.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 1.  0.  1.  0.  1.  0.  1.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]]


In [116]:
#arr3=np.zeros((10,10)) 
arr3=np.random.randint(1,size=(10,10))

In [117]:
print(arr3)

[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]


In [118]:
arr3[1:9,1:9]=1
print(arr3)
 

[[0 0 0 0 0 0 0 0 0 0]
 [0 1 1 1 1 1 1 1 1 0]
 [0 1 1 1 1 1 1 1 1 0]
 [0 1 1 1 1 1 1 1 1 0]
 [0 1 1 1 1 1 1 1 1 0]
 [0 1 1 1 1 1 1 1 1 0]
 [0 1 1 1 1 1 1 1 1 0]
 [0 1 1 1 1 1 1 1 1 0]
 [0 1 1 1 1 1 1 1 1 0]
 [0 0 0 0 0 0 0 0 0 0]]


In [119]:
s1 = pd.Series(np.arange(5))
print(s1)

0    0
1    1
2    2
3    3
4    4
dtype: int32


In [122]:
s1.index=['a','b','c','d','e']
print(s1.keys)
print(s1.values)

<bound method Series.keys of a    0
b    1
c    2
d    3
e    4
dtype: int32>
[0 1 2 3 4]


In [121]:
print(s1)

a    0
b    1
c    2
d    3
e    4
dtype: int32


In [127]:
df01=pd.DataFrame({'语文':[70,80,90],
                    '数学':[97,98,100],
                    '英语':[85,96,96]})
print(df01)

    数学  英语  语文
0   97  85  70
1   98  96  80
2  100  96  90


In [133]:
df01.mean()

数学    98.333333
英语    92.333333
语文    80.000000
dtype: float64

In [132]:
df01.min()

数学    97
英语    85
语文    70
dtype: int64

In [134]:
df01.max()

数学    100
英语     96
语文     90
dtype: int64

In [135]:
df01.add('hell':[NaN,NaN,NaN])

SyntaxError: invalid syntax (<ipython-input-135-9a11a015e04e>, line 1)